/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.records;


import de.dataelementhub.dal.jooq.enums.ElementType;
import de.dataelementhub.dal.jooq.tables.Element;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElementRecord extends UpdatableRecordImpl<ElementRecord> implements Record5<Integer, ElementType, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.element.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.element.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.element.element_type</code>.
     */
    public void setElementType(ElementType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.element.element_type</code>.
     */
    public ElementType getElementType() {
        return (ElementType) get(1);
    }

    /**
     * Setter for <code>public.element.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.element.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.element.element_id</code>.
     */
    public void setElementId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.element.element_id</code>.
     */
    public Integer getElementId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.element.permitted_value</code>.
     */
    public void setPermittedValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.element.permitted_value</code>.
     */
    public String getPermittedValue() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, ElementType, Integer, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, ElementType, Integer, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Element.ELEMENT.ID;
    }

    @Override
    public Field<ElementType> field2() {
        return Element.ELEMENT.ELEMENT_TYPE;
    }

    @Override
    public Field<Integer> field3() {
        return Element.ELEMENT.CREATED_BY;
    }

    @Override
    public Field<Integer> field4() {
        return Element.ELEMENT.ELEMENT_ID;
    }

    @Override
    public Field<String> field5() {
        return Element.ELEMENT.PERMITTED_VALUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public ElementType component2() {
        return getElementType();
    }

    @Override
    public Integer component3() {
        return getCreatedBy();
    }

    @Override
    public Integer component4() {
        return getElementId();
    }

    @Override
    public String component5() {
        return getPermittedValue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public ElementType value2() {
        return getElementType();
    }

    @Override
    public Integer value3() {
        return getCreatedBy();
    }

    @Override
    public Integer value4() {
        return getElementId();
    }

    @Override
    public String value5() {
        return getPermittedValue();
    }

    @Override
    public ElementRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ElementRecord value2(ElementType value) {
        setElementType(value);
        return this;
    }

    @Override
    public ElementRecord value3(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ElementRecord value4(Integer value) {
        setElementId(value);
        return this;
    }

    @Override
    public ElementRecord value5(String value) {
        setPermittedValue(value);
        return this;
    }

    @Override
    public ElementRecord values(Integer value1, ElementType value2, Integer value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElementRecord
     */
    public ElementRecord() {
        super(Element.ELEMENT);
    }

    /**
     * Create a detached, initialised ElementRecord
     */
    public ElementRecord(Integer id, ElementType elementType, Integer createdBy, Integer elementId, String permittedValue) {
        super(Element.ELEMENT);

        setId(id);
        setElementType(elementType);
        setCreatedBy(createdBy);
        setElementId(elementId);
        setPermittedValue(permittedValue);
    }

    /**
     * Create a detached, initialised ElementRecord
     */
    public ElementRecord(de.dataelementhub.dal.jooq.tables.pojos.Element value) {
        super(Element.ELEMENT);

        if (value != null) {
            setId(value.getId());
            setElementType(value.getElementType());
            setCreatedBy(value.getCreatedBy());
            setElementId(value.getElementId());
            setPermittedValue(value.getPermittedValue());
        }
    }
}
