/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.records;


import de.dataelementhub.dal.jooq.enums.ElementType;
import de.dataelementhub.dal.jooq.tables.GetValueDomainByUrn;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetValueDomainByUrnRecord extends TableRecordImpl<GetValueDomainByUrnRecord> implements Record7<Integer, ElementType, Integer, Integer, String, UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_value_domain_by_urn.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.element_type</code>.
     */
    public void setElementType(ElementType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.element_type</code>.
     */
    public ElementType getElementType() {
        return (ElementType) get(1);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.element_id</code>.
     */
    public void setElementId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.element_id</code>.
     */
    public Integer getElementId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.permitted_value</code>.
     */
    public void setPermittedValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.permitted_value</code>.
     */
    public String getPermittedValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.get_value_domain_by_urn.external_id</code>.
     */
    public void setExternalId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.get_value_domain_by_urn.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, ElementType, Integer, Integer, String, UUID, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, ElementType, Integer, Integer, String, UUID, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.ID;
    }

    @Override
    public Field<ElementType> field2() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.ELEMENT_TYPE;
    }

    @Override
    public Field<Integer> field3() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.CREATED_BY;
    }

    @Override
    public Field<Integer> field4() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.ELEMENT_ID;
    }

    @Override
    public Field<String> field5() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.PERMITTED_VALUE;
    }

    @Override
    public Field<UUID> field6() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.UUID;
    }

    @Override
    public Field<String> field7() {
        return GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN.EXTERNAL_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public ElementType component2() {
        return getElementType();
    }

    @Override
    public Integer component3() {
        return getCreatedBy();
    }

    @Override
    public Integer component4() {
        return getElementId();
    }

    @Override
    public String component5() {
        return getPermittedValue();
    }

    @Override
    public UUID component6() {
        return getUuid();
    }

    @Override
    public String component7() {
        return getExternalId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public ElementType value2() {
        return getElementType();
    }

    @Override
    public Integer value3() {
        return getCreatedBy();
    }

    @Override
    public Integer value4() {
        return getElementId();
    }

    @Override
    public String value5() {
        return getPermittedValue();
    }

    @Override
    public UUID value6() {
        return getUuid();
    }

    @Override
    public String value7() {
        return getExternalId();
    }

    @Override
    public GetValueDomainByUrnRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value2(ElementType value) {
        setElementType(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value3(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value4(Integer value) {
        setElementId(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value5(String value) {
        setPermittedValue(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value6(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord value7(String value) {
        setExternalId(value);
        return this;
    }

    @Override
    public GetValueDomainByUrnRecord values(Integer value1, ElementType value2, Integer value3, Integer value4, String value5, UUID value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetValueDomainByUrnRecord
     */
    public GetValueDomainByUrnRecord() {
        super(GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN);
    }

    /**
     * Create a detached, initialised GetValueDomainByUrnRecord
     */
    public GetValueDomainByUrnRecord(Integer id, ElementType elementType, Integer createdBy, Integer elementId, String permittedValue, UUID uuid, String externalId) {
        super(GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN);

        setId(id);
        setElementType(elementType);
        setCreatedBy(createdBy);
        setElementId(elementId);
        setPermittedValue(permittedValue);
        setUuid(uuid);
        setExternalId(externalId);
    }

    /**
     * Create a detached, initialised GetValueDomainByUrnRecord
     */
    public GetValueDomainByUrnRecord(de.dataelementhub.dal.jooq.tables.pojos.GetValueDomainByUrn value) {
        super(GetValueDomainByUrn.GET_VALUE_DOMAIN_BY_URN);

        if (value != null) {
            setId(value.getId());
            setElementType(value.getElementType());
            setCreatedBy(value.getCreatedBy());
            setElementId(value.getElementId());
            setPermittedValue(value.getPermittedValue());
            setUuid(value.getUuid());
            setExternalId(value.getExternalId());
        }
    }
}
