/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.records;


import de.dataelementhub.dal.jooq.enums.Status;
import de.dataelementhub.dal.jooq.tables.ScopedIdentifier;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierRecord extends UpdatableRecordImpl<ScopedIdentifierRecord> implements Record8<Integer, Integer, Integer, Integer, Status, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.scoped_identifier.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.scoped_identifier.revision</code>.
     */
    public void setRevision(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.revision</code>.
     */
    public Integer getRevision() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.scoped_identifier.identifier</code>.
     */
    public void setIdentifier(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.identifier</code>.
     */
    public Integer getIdentifier() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.scoped_identifier.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.scoped_identifier.status</code>.
     */
    public void setStatus(Status value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.status</code>.
     */
    public Status getStatus() {
        return (Status) get(4);
    }

    /**
     * Setter for <code>public.scoped_identifier.element_id</code>.
     */
    public void setElementId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.element_id</code>.
     */
    public Integer getElementId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.scoped_identifier.namespace_id</code>.
     */
    public void setNamespaceId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.namespace_id</code>.
     */
    public Integer getNamespaceId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.scoped_identifier.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.scoped_identifier.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, Integer, Status, Integer, Integer, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, Integer, Status, Integer, Integer, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.REVISION;
    }

    @Override
    public Field<Integer> field3() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.IDENTIFIER;
    }

    @Override
    public Field<Integer> field4() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.CREATED_BY;
    }

    @Override
    public Field<Status> field5() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.STATUS;
    }

    @Override
    public Field<Integer> field6() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.ELEMENT_ID;
    }

    @Override
    public Field<Integer> field7() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.NAMESPACE_ID;
    }

    @Override
    public Field<Boolean> field8() {
        return ScopedIdentifier.SCOPED_IDENTIFIER.HIDDEN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRevision();
    }

    @Override
    public Integer component3() {
        return getIdentifier();
    }

    @Override
    public Integer component4() {
        return getCreatedBy();
    }

    @Override
    public Status component5() {
        return getStatus();
    }

    @Override
    public Integer component6() {
        return getElementId();
    }

    @Override
    public Integer component7() {
        return getNamespaceId();
    }

    @Override
    public Boolean component8() {
        return getHidden();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRevision();
    }

    @Override
    public Integer value3() {
        return getIdentifier();
    }

    @Override
    public Integer value4() {
        return getCreatedBy();
    }

    @Override
    public Status value5() {
        return getStatus();
    }

    @Override
    public Integer value6() {
        return getElementId();
    }

    @Override
    public Integer value7() {
        return getNamespaceId();
    }

    @Override
    public Boolean value8() {
        return getHidden();
    }

    @Override
    public ScopedIdentifierRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value2(Integer value) {
        setRevision(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value3(Integer value) {
        setIdentifier(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value4(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value5(Status value) {
        setStatus(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value6(Integer value) {
        setElementId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value7(Integer value) {
        setNamespaceId(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord value8(Boolean value) {
        setHidden(value);
        return this;
    }

    @Override
    public ScopedIdentifierRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Status value5, Integer value6, Integer value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScopedIdentifierRecord
     */
    public ScopedIdentifierRecord() {
        super(ScopedIdentifier.SCOPED_IDENTIFIER);
    }

    /**
     * Create a detached, initialised ScopedIdentifierRecord
     */
    public ScopedIdentifierRecord(Integer id, Integer revision, Integer identifier, Integer createdBy, Status status, Integer elementId, Integer namespaceId, Boolean hidden) {
        super(ScopedIdentifier.SCOPED_IDENTIFIER);

        setId(id);
        setRevision(revision);
        setIdentifier(identifier);
        setCreatedBy(createdBy);
        setStatus(status);
        setElementId(elementId);
        setNamespaceId(namespaceId);
        setHidden(hidden);
    }

    /**
     * Create a detached, initialised ScopedIdentifierRecord
     */
    public ScopedIdentifierRecord(de.dataelementhub.dal.jooq.tables.pojos.ScopedIdentifier value) {
        super(ScopedIdentifier.SCOPED_IDENTIFIER);

        if (value != null) {
            setId(value.getId());
            setRevision(value.getRevision());
            setIdentifier(value.getIdentifier());
            setCreatedBy(value.getCreatedBy());
            setStatus(value.getStatus());
            setElementId(value.getElementId());
            setNamespaceId(value.getNamespaceId());
            setHidden(value.getHidden());
        }
    }
}
