/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.records;


import de.dataelementhub.dal.jooq.enums.SourceType;
import de.dataelementhub.dal.jooq.tables.Source;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceRecord extends UpdatableRecordImpl<SourceRecord> implements Record5<Integer, String, String, String, SourceType> {

    private static final long serialVersionUID = 323969356;

    /**
     * Setter for <code>public.source.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.source.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.source.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.source.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.source.prefix</code>.
     */
    public void setPrefix(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.source.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.source.base_url</code>.
     */
    public void setBaseUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.source.base_url</code>.
     */
    public String getBaseUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.source.type</code>.
     */
    public void setType(SourceType value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.source.type</code>.
     */
    public SourceType getType() {
        return (SourceType) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, SourceType> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, SourceType> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Source.SOURCE.ID;
    }

    @Override
    public Field<String> field2() {
        return Source.SOURCE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Source.SOURCE.PREFIX;
    }

    @Override
    public Field<String> field4() {
        return Source.SOURCE.BASE_URL;
    }

    @Override
    public Field<SourceType> field5() {
        return Source.SOURCE.TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPrefix();
    }

    @Override
    public String component4() {
        return getBaseUrl();
    }

    @Override
    public SourceType component5() {
        return getType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPrefix();
    }

    @Override
    public String value4() {
        return getBaseUrl();
    }

    @Override
    public SourceType value5() {
        return getType();
    }

    @Override
    public SourceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SourceRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SourceRecord value3(String value) {
        setPrefix(value);
        return this;
    }

    @Override
    public SourceRecord value4(String value) {
        setBaseUrl(value);
        return this;
    }

    @Override
    public SourceRecord value5(SourceType value) {
        setType(value);
        return this;
    }

    @Override
    public SourceRecord values(Integer value1, String value2, String value3, String value4, SourceType value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceRecord
     */
    public SourceRecord() {
        super(Source.SOURCE);
    }

    /**
     * Create a detached, initialised SourceRecord
     */
    public SourceRecord(Integer id, String name, String prefix, String baseUrl, SourceType type) {
        super(Source.SOURCE);

        set(0, id);
        set(1, name);
        set(2, prefix);
        set(3, baseUrl);
        set(4, type);
    }
}
