/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.routines;


import de.dataelementhub.dal.jooq.Public;
import de.dataelementhub.dal.jooq.tables.records.ScopedIdentifierRecord;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetNamespaceScopedIdentifierByUrn extends AbstractRoutine<ScopedIdentifierRecord> {

    private static final long serialVersionUID = 1721717771;

    /**
     * The parameter <code>public.get_namespace_scoped_identifier_by_urn.RETURN_VALUE</code>.
     */
    public static final Parameter<ScopedIdentifierRecord> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", de.dataelementhub.dal.jooq.tables.ScopedIdentifier.SCOPED_IDENTIFIER.getDataType(), false, false);

    /**
     * The parameter <code>public.get_namespace_scoped_identifier_by_urn.urn</code>.
     */
    public static final Parameter<String> URN = Internal.createParameter("urn", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public GetNamespaceScopedIdentifierByUrn() {
        super("get_namespace_scoped_identifier_by_urn", Public.PUBLIC, de.dataelementhub.dal.jooq.tables.ScopedIdentifier.SCOPED_IDENTIFIER.getDataType());

        setReturnParameter(RETURN_VALUE);
        addInParameter(URN);
    }

    /**
     * Set the <code>urn</code> parameter IN value to the routine
     */
    public void setUrn(String value) {
        setValue(URN, value);
    }

    /**
     * Set the <code>urn</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUrn(Field<String> field) {
        setField(URN, field);
    }
}
