/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import de.dataelementhub.dal.jooq.enums.RelationType;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConceptElementAssociation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       conceptId;
    private Integer       scopedidentifierId;
    private RelationType  linktype;
    private Integer       createdBy;
    private LocalDateTime createdAt;

    public ConceptElementAssociation() {}

    public ConceptElementAssociation(ConceptElementAssociation value) {
        this.conceptId = value.conceptId;
        this.scopedidentifierId = value.scopedidentifierId;
        this.linktype = value.linktype;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
    }

    public ConceptElementAssociation(
        Integer       conceptId,
        Integer       scopedidentifierId,
        RelationType  linktype,
        Integer       createdBy,
        LocalDateTime createdAt
    ) {
        this.conceptId = conceptId;
        this.scopedidentifierId = scopedidentifierId;
        this.linktype = linktype;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.concept_element_association.concept_id</code>.
     */
    public Integer getConceptId() {
        return this.conceptId;
    }

    /**
     * Setter for <code>public.concept_element_association.concept_id</code>.
     */
    public void setConceptId(Integer conceptId) {
        this.conceptId = conceptId;
    }

    /**
     * Getter for
     * <code>public.concept_element_association.scopedidentifier_id</code>.
     */
    public Integer getScopedidentifierId() {
        return this.scopedidentifierId;
    }

    /**
     * Setter for
     * <code>public.concept_element_association.scopedidentifier_id</code>.
     */
    public void setScopedidentifierId(Integer scopedidentifierId) {
        this.scopedidentifierId = scopedidentifierId;
    }

    /**
     * Getter for <code>public.concept_element_association.linktype</code>.
     */
    public RelationType getLinktype() {
        return this.linktype;
    }

    /**
     * Setter for <code>public.concept_element_association.linktype</code>.
     */
    public void setLinktype(RelationType linktype) {
        this.linktype = linktype;
    }

    /**
     * Getter for <code>public.concept_element_association.created_by</code>.
     */
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.concept_element_association.created_by</code>.
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.concept_element_association.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.concept_element_association.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConceptElementAssociation (");

        sb.append(conceptId);
        sb.append(", ").append(scopedidentifierId);
        sb.append(", ").append(linktype);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
