/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Concept implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        system;
    private String        version;
    private String        term;
    private String        text;
    private Integer       sourceId;
    private Integer       createdBy;
    private LocalDateTime createdAt;

    public Concept() {}

    public Concept(Concept value) {
        this.id = value.id;
        this.system = value.system;
        this.version = value.version;
        this.term = value.term;
        this.text = value.text;
        this.sourceId = value.sourceId;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
    }

    public Concept(
        Integer       id,
        String        system,
        String        version,
        String        term,
        String        text,
        Integer       sourceId,
        Integer       createdBy,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.system = system;
        this.version = version;
        this.term = term;
        this.text = text;
        this.sourceId = sourceId;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.concept.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.concept.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.concept.system</code>.
     */
    public String getSystem() {
        return this.system;
    }

    /**
     * Setter for <code>public.concept.system</code>.
     */
    public void setSystem(String system) {
        this.system = system;
    }

    /**
     * Getter for <code>public.concept.version</code>.
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.concept.version</code>.
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for <code>public.concept.term</code>.
     */
    public String getTerm() {
        return this.term;
    }

    /**
     * Setter for <code>public.concept.term</code>.
     */
    public void setTerm(String term) {
        this.term = term;
    }

    /**
     * Getter for <code>public.concept.text</code>.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Setter for <code>public.concept.text</code>.
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for <code>public.concept.source_id</code>.
     */
    public Integer getSourceId() {
        return this.sourceId;
    }

    /**
     * Setter for <code>public.concept.source_id</code>.
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * Getter for <code>public.concept.created_by</code>.
     */
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.concept.created_by</code>.
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.concept.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.concept.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Concept (");

        sb.append(id);
        sb.append(", ").append(system);
        sb.append(", ").append(version);
        sb.append(", ").append(term);
        sb.append(", ").append(text);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
