/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Definition implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer scopedIdentifierId;
    private String designation;
    private String definition;
    private String language;
    private Integer elementId;

    public Definition() {}

    public Definition(Definition value) {
        this.id = value.id;
        this.scopedIdentifierId = value.scopedIdentifierId;
        this.designation = value.designation;
        this.definition = value.definition;
        this.language = value.language;
        this.elementId = value.elementId;
    }

    public Definition(
        Integer id,
        Integer scopedIdentifierId,
        String designation,
        String definition,
        String language,
        Integer elementId
    ) {
        this.id = id;
        this.scopedIdentifierId = scopedIdentifierId;
        this.designation = designation;
        this.definition = definition;
        this.language = language;
        this.elementId = elementId;
    }

    /**
     * Getter for <code>public.definition.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.definition.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.definition.scoped_identifier_id</code>.
     */
    public Integer getScopedIdentifierId() {
        return this.scopedIdentifierId;
    }

    /**
     * Setter for <code>public.definition.scoped_identifier_id</code>.
     */
    public void setScopedIdentifierId(Integer scopedIdentifierId) {
        this.scopedIdentifierId = scopedIdentifierId;
    }

    /**
     * Getter for <code>public.definition.designation</code>.
     */
    public String getDesignation() {
        return this.designation;
    }

    /**
     * Setter for <code>public.definition.designation</code>.
     */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /**
     * Getter for <code>public.definition.definition</code>.
     */
    public String getDefinition() {
        return this.definition;
    }

    /**
     * Setter for <code>public.definition.definition</code>.
     */
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    /**
     * Getter for <code>public.definition.language</code>.
     */
    public String getLanguage() {
        return this.language;
    }

    /**
     * Setter for <code>public.definition.language</code>.
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Getter for <code>public.definition.element_id</code>.
     */
    public Integer getElementId() {
        return this.elementId;
    }

    /**
     * Setter for <code>public.definition.element_id</code>.
     */
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Definition other = (Definition) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.scopedIdentifierId == null) {
            if (other.scopedIdentifierId != null)
                return false;
        }
        else if (!this.scopedIdentifierId.equals(other.scopedIdentifierId))
            return false;
        if (this.designation == null) {
            if (other.designation != null)
                return false;
        }
        else if (!this.designation.equals(other.designation))
            return false;
        if (this.definition == null) {
            if (other.definition != null)
                return false;
        }
        else if (!this.definition.equals(other.definition))
            return false;
        if (this.language == null) {
            if (other.language != null)
                return false;
        }
        else if (!this.language.equals(other.language))
            return false;
        if (this.elementId == null) {
            if (other.elementId != null)
                return false;
        }
        else if (!this.elementId.equals(other.elementId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.scopedIdentifierId == null) ? 0 : this.scopedIdentifierId.hashCode());
        result = prime * result + ((this.designation == null) ? 0 : this.designation.hashCode());
        result = prime * result + ((this.definition == null) ? 0 : this.definition.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        result = prime * result + ((this.elementId == null) ? 0 : this.elementId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Definition (");

        sb.append(id);
        sb.append(", ").append(scopedIdentifierId);
        sb.append(", ").append(designation);
        sb.append(", ").append(definition);
        sb.append(", ").append(language);
        sb.append(", ").append(elementId);

        sb.append(")");
        return sb.toString();
    }
}
