/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import de.dataelementhub.dal.jooq.enums.ElementType;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Element implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer     id;
    private ElementType elementType;
    private Integer     createdBy;
    private Integer     elementId;
    private String      permittedValue;
    private UUID        uuid;
    private String      externalId;

    public Element() {}

    public Element(Element value) {
        this.id = value.id;
        this.elementType = value.elementType;
        this.createdBy = value.createdBy;
        this.elementId = value.elementId;
        this.permittedValue = value.permittedValue;
        this.uuid = value.uuid;
        this.externalId = value.externalId;
    }

    public Element(
        Integer     id,
        ElementType elementType,
        Integer     createdBy,
        Integer     elementId,
        String      permittedValue,
        UUID        uuid,
        String      externalId
    ) {
        this.id = id;
        this.elementType = elementType;
        this.createdBy = createdBy;
        this.elementId = elementId;
        this.permittedValue = permittedValue;
        this.uuid = uuid;
        this.externalId = externalId;
    }

    /**
     * Getter for <code>public.element.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.element.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.element.element_type</code>.
     */
    public ElementType getElementType() {
        return this.elementType;
    }

    /**
     * Setter for <code>public.element.element_type</code>.
     */
    public void setElementType(ElementType elementType) {
        this.elementType = elementType;
    }

    /**
     * Getter for <code>public.element.created_by</code>.
     */
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.element.created_by</code>.
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.element.element_id</code>.
     */
    public Integer getElementId() {
        return this.elementId;
    }

    /**
     * Setter for <code>public.element.element_id</code>.
     */
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    /**
     * Getter for <code>public.element.permitted_value</code>.
     */
    public String getPermittedValue() {
        return this.permittedValue;
    }

    /**
     * Setter for <code>public.element.permitted_value</code>.
     */
    public void setPermittedValue(String permittedValue) {
        this.permittedValue = permittedValue;
    }

    /**
     * Getter for <code>public.element.uuid</code>.
     */
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.element.uuid</code>.
     */
    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>public.element.external_id</code>.
     */
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Setter for <code>public.element.external_id</code>.
     */
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Element (");

        sb.append(id);
        sb.append(", ").append(elementType);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(elementId);
        sb.append(", ").append(permittedValue);
        sb.append(", ").append(uuid);
        sb.append(", ").append(externalId);

        sb.append(")");
        return sb.toString();
    }
}
