/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import de.dataelementhub.dal.jooq.enums.RelationType;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElementRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        leftUrn;
    private Integer       leftSource;
    private String        rightUrn;
    private Integer       rightSource;
    private RelationType  relation;
    private Integer       createdBy;
    private LocalDateTime createdAt;

    public ElementRelation() {}

    public ElementRelation(ElementRelation value) {
        this.leftUrn = value.leftUrn;
        this.leftSource = value.leftSource;
        this.rightUrn = value.rightUrn;
        this.rightSource = value.rightSource;
        this.relation = value.relation;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
    }

    public ElementRelation(
        String        leftUrn,
        Integer       leftSource,
        String        rightUrn,
        Integer       rightSource,
        RelationType  relation,
        Integer       createdBy,
        LocalDateTime createdAt
    ) {
        this.leftUrn = leftUrn;
        this.leftSource = leftSource;
        this.rightUrn = rightUrn;
        this.rightSource = rightSource;
        this.relation = relation;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.element_relation.left_urn</code>.
     */
    public String getLeftUrn() {
        return this.leftUrn;
    }

    /**
     * Setter for <code>public.element_relation.left_urn</code>.
     */
    public void setLeftUrn(String leftUrn) {
        this.leftUrn = leftUrn;
    }

    /**
     * Getter for <code>public.element_relation.left_source</code>.
     */
    public Integer getLeftSource() {
        return this.leftSource;
    }

    /**
     * Setter for <code>public.element_relation.left_source</code>.
     */
    public void setLeftSource(Integer leftSource) {
        this.leftSource = leftSource;
    }

    /**
     * Getter for <code>public.element_relation.right_urn</code>.
     */
    public String getRightUrn() {
        return this.rightUrn;
    }

    /**
     * Setter for <code>public.element_relation.right_urn</code>.
     */
    public void setRightUrn(String rightUrn) {
        this.rightUrn = rightUrn;
    }

    /**
     * Getter for <code>public.element_relation.right_source</code>.
     */
    public Integer getRightSource() {
        return this.rightSource;
    }

    /**
     * Setter for <code>public.element_relation.right_source</code>.
     */
    public void setRightSource(Integer rightSource) {
        this.rightSource = rightSource;
    }

    /**
     * Getter for <code>public.element_relation.relation</code>.
     */
    public RelationType getRelation() {
        return this.relation;
    }

    /**
     * Setter for <code>public.element_relation.relation</code>.
     */
    public void setRelation(RelationType relation) {
        this.relation = relation;
    }

    /**
     * Getter for <code>public.element_relation.created_by</code>.
     */
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.element_relation.created_by</code>.
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.element_relation.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.element_relation.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElementRelation (");

        sb.append(leftUrn);
        sb.append(", ").append(leftSource);
        sb.append(", ").append(rightUrn);
        sb.append(", ").append(rightSource);
        sb.append(", ").append(relation);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
