/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissibleCode implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer codeScopedIdentifierId;
    private Integer catalogValueDomainId;

    public PermissibleCode() {}

    public PermissibleCode(PermissibleCode value) {
        this.codeScopedIdentifierId = value.codeScopedIdentifierId;
        this.catalogValueDomainId = value.catalogValueDomainId;
    }

    public PermissibleCode(
        Integer codeScopedIdentifierId,
        Integer catalogValueDomainId
    ) {
        this.codeScopedIdentifierId = codeScopedIdentifierId;
        this.catalogValueDomainId = catalogValueDomainId;
    }

    /**
     * Getter for
     * <code>public.permissible_code.code_scoped_identifier_id</code>.
     */
    public Integer getCodeScopedIdentifierId() {
        return this.codeScopedIdentifierId;
    }

    /**
     * Setter for
     * <code>public.permissible_code.code_scoped_identifier_id</code>.
     */
    public void setCodeScopedIdentifierId(Integer codeScopedIdentifierId) {
        this.codeScopedIdentifierId = codeScopedIdentifierId;
    }

    /**
     * Getter for <code>public.permissible_code.catalog_value_domain_id</code>.
     */
    public Integer getCatalogValueDomainId() {
        return this.catalogValueDomainId;
    }

    /**
     * Setter for <code>public.permissible_code.catalog_value_domain_id</code>.
     */
    public void setCatalogValueDomainId(Integer catalogValueDomainId) {
        this.catalogValueDomainId = catalogValueDomainId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PermissibleCode other = (PermissibleCode) obj;
        if (this.codeScopedIdentifierId == null) {
            if (other.codeScopedIdentifierId != null)
                return false;
        }
        else if (!this.codeScopedIdentifierId.equals(other.codeScopedIdentifierId))
            return false;
        if (this.catalogValueDomainId == null) {
            if (other.catalogValueDomainId != null)
                return false;
        }
        else if (!this.catalogValueDomainId.equals(other.catalogValueDomainId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.codeScopedIdentifierId == null) ? 0 : this.codeScopedIdentifierId.hashCode());
        result = prime * result + ((this.catalogValueDomainId == null) ? 0 : this.catalogValueDomainId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PermissibleCode (");

        sb.append(codeScopedIdentifierId);
        sb.append(", ").append(catalogValueDomainId);

        sb.append(")");
        return sb.toString();
    }
}
