/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import de.dataelementhub.dal.jooq.enums.ElementType;
import de.dataelementhub.dal.jooq.enums.Status;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierSimplified implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer     id;
    private String      urn;
    private Integer     identifier;
    private Integer     revision;
    private Status      status;
    private ElementType elementType;
    private Integer     elementId;
    private Integer     namespaceId;
    private String      namespaceUrn;

    public ScopedIdentifierSimplified() {}

    public ScopedIdentifierSimplified(ScopedIdentifierSimplified value) {
        this.id = value.id;
        this.urn = value.urn;
        this.identifier = value.identifier;
        this.revision = value.revision;
        this.status = value.status;
        this.elementType = value.elementType;
        this.elementId = value.elementId;
        this.namespaceId = value.namespaceId;
        this.namespaceUrn = value.namespaceUrn;
    }

    public ScopedIdentifierSimplified(
        Integer     id,
        String      urn,
        Integer     identifier,
        Integer     revision,
        Status      status,
        ElementType elementType,
        Integer     elementId,
        Integer     namespaceId,
        String      namespaceUrn
    ) {
        this.id = id;
        this.urn = urn;
        this.identifier = identifier;
        this.revision = revision;
        this.status = status;
        this.elementType = elementType;
        this.elementId = elementId;
        this.namespaceId = namespaceId;
        this.namespaceUrn = namespaceUrn;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.urn</code>.
     */
    public String getUrn() {
        return this.urn;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.urn</code>.
     */
    public void setUrn(String urn) {
        this.urn = urn;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.identifier</code>.
     */
    public Integer getIdentifier() {
        return this.identifier;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.identifier</code>.
     */
    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.revision</code>.
     */
    public Integer getRevision() {
        return this.revision;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.revision</code>.
     */
    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.status</code>.
     */
    public Status getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.status</code>.
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.element_type</code>.
     */
    public ElementType getElementType() {
        return this.elementType;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.element_type</code>.
     */
    public void setElementType(ElementType elementType) {
        this.elementType = elementType;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.element_id</code>.
     */
    public Integer getElementId() {
        return this.elementId;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.element_id</code>.
     */
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    /**
     * Getter for <code>public.scoped_identifier_simplified.namespace_id</code>.
     */
    public Integer getNamespaceId() {
        return this.namespaceId;
    }

    /**
     * Setter for <code>public.scoped_identifier_simplified.namespace_id</code>.
     */
    public void setNamespaceId(Integer namespaceId) {
        this.namespaceId = namespaceId;
    }

    /**
     * Getter for
     * <code>public.scoped_identifier_simplified.namespace_urn</code>.
     */
    public String getNamespaceUrn() {
        return this.namespaceUrn;
    }

    /**
     * Setter for
     * <code>public.scoped_identifier_simplified.namespace_urn</code>.
     */
    public void setNamespaceUrn(String namespaceUrn) {
        this.namespaceUrn = namespaceUrn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScopedIdentifierSimplified (");

        sb.append(id);
        sb.append(", ").append(urn);
        sb.append(", ").append(identifier);
        sb.append(", ").append(revision);
        sb.append(", ").append(status);
        sb.append(", ").append(elementType);
        sb.append(", ").append(elementId);
        sb.append(", ").append(namespaceId);
        sb.append(", ").append(namespaceUrn);

        sb.append(")");
        return sb.toString();
    }
}
