/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Slot implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer scopedIdentifierId;
    private String key;
    private String value;

    public Slot() {}

    public Slot(Slot value) {
        this.id = value.id;
        this.scopedIdentifierId = value.scopedIdentifierId;
        this.key = value.key;
        this.value = value.value;
    }

    public Slot(
        Integer id,
        Integer scopedIdentifierId,
        String key,
        String value
    ) {
        this.id = id;
        this.scopedIdentifierId = scopedIdentifierId;
        this.key = key;
        this.value = value;
    }

    /**
     * Getter for <code>public.slot.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.slot.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.slot.scoped_identifier_id</code>.
     */
    public Integer getScopedIdentifierId() {
        return this.scopedIdentifierId;
    }

    /**
     * Setter for <code>public.slot.scoped_identifier_id</code>.
     */
    public void setScopedIdentifierId(Integer scopedIdentifierId) {
        this.scopedIdentifierId = scopedIdentifierId;
    }

    /**
     * Getter for <code>public.slot.key</code>.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>public.slot.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>public.slot.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>public.slot.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Slot other = (Slot) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.scopedIdentifierId == null) {
            if (other.scopedIdentifierId != null)
                return false;
        }
        else if (!this.scopedIdentifierId.equals(other.scopedIdentifierId))
            return false;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.scopedIdentifierId == null) ? 0 : this.scopedIdentifierId.hashCode());
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Slot (");

        sb.append(id);
        sb.append(", ").append(scopedIdentifierId);
        sb.append(", ").append(key);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
