/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import de.dataelementhub.dal.jooq.enums.SourceType;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Source implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer    id;
    private String     name;
    private String     prefix;
    private String     baseUrl;
    private SourceType type;

    public Source() {}

    public Source(Source value) {
        this.id = value.id;
        this.name = value.name;
        this.prefix = value.prefix;
        this.baseUrl = value.baseUrl;
        this.type = value.type;
    }

    public Source(
        Integer    id,
        String     name,
        String     prefix,
        String     baseUrl,
        SourceType type
    ) {
        this.id = id;
        this.name = name;
        this.prefix = prefix;
        this.baseUrl = baseUrl;
        this.type = type;
    }

    /**
     * Getter for <code>public.source.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.source.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.source.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.source.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.source.prefix</code>.
     */
    public String getPrefix() {
        return this.prefix;
    }

    /**
     * Setter for <code>public.source.prefix</code>.
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * Getter for <code>public.source.base_url</code>.
     */
    public String getBaseUrl() {
        return this.baseUrl;
    }

    /**
     * Setter for <code>public.source.base_url</code>.
     */
    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl;
    }

    /**
     * Getter for <code>public.source.type</code>.
     */
    public SourceType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.source.type</code>.
     */
    public void setType(SourceType type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Source (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(prefix);
        sb.append(", ").append(baseUrl);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
