/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import de.dataelementhub.dal.jooq.enums.ElementType;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staging implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String data;
    private ElementType elementType;
    private String designation;
    private Integer importId;
    private Integer scopedIdentifierId;
    private LocalDateTime convertedAt;
    private Integer convertedBy;
    private String stagedElementId;
    private String members;

    public Staging() {}

    public Staging(Staging value) {
        this.id = value.id;
        this.data = value.data;
        this.elementType = value.elementType;
        this.designation = value.designation;
        this.importId = value.importId;
        this.scopedIdentifierId = value.scopedIdentifierId;
        this.convertedAt = value.convertedAt;
        this.convertedBy = value.convertedBy;
        this.stagedElementId = value.stagedElementId;
        this.members = value.members;
    }

    public Staging(
        Integer id,
        String data,
        ElementType elementType,
        String designation,
        Integer importId,
        Integer scopedIdentifierId,
        LocalDateTime convertedAt,
        Integer convertedBy,
        String stagedElementId,
        String members
    ) {
        this.id = id;
        this.data = data;
        this.elementType = elementType;
        this.designation = designation;
        this.importId = importId;
        this.scopedIdentifierId = scopedIdentifierId;
        this.convertedAt = convertedAt;
        this.convertedBy = convertedBy;
        this.stagedElementId = stagedElementId;
        this.members = members;
    }

    /**
     * Getter for <code>public.staging.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.staging.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.staging.data</code>.
     */
    public String getData() {
        return this.data;
    }

    /**
     * Setter for <code>public.staging.data</code>.
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     * Getter for <code>public.staging.element_type</code>.
     */
    public ElementType getElementType() {
        return this.elementType;
    }

    /**
     * Setter for <code>public.staging.element_type</code>.
     */
    public void setElementType(ElementType elementType) {
        this.elementType = elementType;
    }

    /**
     * Getter for <code>public.staging.designation</code>.
     */
    public String getDesignation() {
        return this.designation;
    }

    /**
     * Setter for <code>public.staging.designation</code>.
     */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /**
     * Getter for <code>public.staging.import_id</code>.
     */
    public Integer getImportId() {
        return this.importId;
    }

    /**
     * Setter for <code>public.staging.import_id</code>.
     */
    public void setImportId(Integer importId) {
        this.importId = importId;
    }

    /**
     * Getter for <code>public.staging.scoped_identifier_id</code>.
     */
    public Integer getScopedIdentifierId() {
        return this.scopedIdentifierId;
    }

    /**
     * Setter for <code>public.staging.scoped_identifier_id</code>.
     */
    public void setScopedIdentifierId(Integer scopedIdentifierId) {
        this.scopedIdentifierId = scopedIdentifierId;
    }

    /**
     * Getter for <code>public.staging.converted_at</code>.
     */
    public LocalDateTime getConvertedAt() {
        return this.convertedAt;
    }

    /**
     * Setter for <code>public.staging.converted_at</code>.
     */
    public void setConvertedAt(LocalDateTime convertedAt) {
        this.convertedAt = convertedAt;
    }

    /**
     * Getter for <code>public.staging.converted_by</code>.
     */
    public Integer getConvertedBy() {
        return this.convertedBy;
    }

    /**
     * Setter for <code>public.staging.converted_by</code>.
     */
    public void setConvertedBy(Integer convertedBy) {
        this.convertedBy = convertedBy;
    }

    /**
     * Getter for <code>public.staging.staged_element_id</code>.
     */
    public String getStagedElementId() {
        return this.stagedElementId;
    }

    /**
     * Setter for <code>public.staging.staged_element_id</code>.
     */
    public void setStagedElementId(String stagedElementId) {
        this.stagedElementId = stagedElementId;
    }

    /**
     * Getter for <code>public.staging.members</code>.
     */
    public String getMembers() {
        return this.members;
    }

    /**
     * Setter for <code>public.staging.members</code>.
     */
    public void setMembers(String members) {
        this.members = members;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Staging other = (Staging) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.data == null) {
            if (other.data != null)
                return false;
        }
        else if (!this.data.equals(other.data))
            return false;
        if (this.elementType == null) {
            if (other.elementType != null)
                return false;
        }
        else if (!this.elementType.equals(other.elementType))
            return false;
        if (this.designation == null) {
            if (other.designation != null)
                return false;
        }
        else if (!this.designation.equals(other.designation))
            return false;
        if (this.importId == null) {
            if (other.importId != null)
                return false;
        }
        else if (!this.importId.equals(other.importId))
            return false;
        if (this.scopedIdentifierId == null) {
            if (other.scopedIdentifierId != null)
                return false;
        }
        else if (!this.scopedIdentifierId.equals(other.scopedIdentifierId))
            return false;
        if (this.convertedAt == null) {
            if (other.convertedAt != null)
                return false;
        }
        else if (!this.convertedAt.equals(other.convertedAt))
            return false;
        if (this.convertedBy == null) {
            if (other.convertedBy != null)
                return false;
        }
        else if (!this.convertedBy.equals(other.convertedBy))
            return false;
        if (this.stagedElementId == null) {
            if (other.stagedElementId != null)
                return false;
        }
        else if (!this.stagedElementId.equals(other.stagedElementId))
            return false;
        if (this.members == null) {
            if (other.members != null)
                return false;
        }
        else if (!this.members.equals(other.members))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.data == null) ? 0 : this.data.hashCode());
        result = prime * result + ((this.elementType == null) ? 0 : this.elementType.hashCode());
        result = prime * result + ((this.designation == null) ? 0 : this.designation.hashCode());
        result = prime * result + ((this.importId == null) ? 0 : this.importId.hashCode());
        result = prime * result + ((this.scopedIdentifierId == null) ? 0 : this.scopedIdentifierId.hashCode());
        result = prime * result + ((this.convertedAt == null) ? 0 : this.convertedAt.hashCode());
        result = prime * result + ((this.convertedBy == null) ? 0 : this.convertedBy.hashCode());
        result = prime * result + ((this.stagedElementId == null) ? 0 : this.stagedElementId.hashCode());
        result = prime * result + ((this.members == null) ? 0 : this.members.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Staging (");

        sb.append(id);
        sb.append(", ").append(data);
        sb.append(", ").append(elementType);
        sb.append(", ").append(designation);
        sb.append(", ").append(importId);
        sb.append(", ").append(scopedIdentifierId);
        sb.append(", ").append(convertedAt);
        sb.append(", ").append(convertedBy);
        sb.append(", ").append(stagedElementId);
        sb.append(", ").append(members);

        sb.append(")");
        return sb.toString();
    }
}
