/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSourceCredentials implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer userId;
    private String credential;
    private Integer sourceId;

    public UserSourceCredentials() {}

    public UserSourceCredentials(UserSourceCredentials value) {
        this.userId = value.userId;
        this.credential = value.credential;
        this.sourceId = value.sourceId;
    }

    public UserSourceCredentials(
        Integer userId,
        String credential,
        Integer sourceId
    ) {
        this.userId = userId;
        this.credential = credential;
        this.sourceId = sourceId;
    }

    /**
     * Getter for <code>public.user_source_credentials.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.user_source_credentials.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.user_source_credentials.credential</code>.
     */
    public String getCredential() {
        return this.credential;
    }

    /**
     * Setter for <code>public.user_source_credentials.credential</code>.
     */
    public void setCredential(String credential) {
        this.credential = credential;
    }

    /**
     * Getter for <code>public.user_source_credentials.source_id</code>.
     */
    public Integer getSourceId() {
        return this.sourceId;
    }

    /**
     * Setter for <code>public.user_source_credentials.source_id</code>.
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserSourceCredentials other = (UserSourceCredentials) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.credential == null) {
            if (other.credential != null)
                return false;
        }
        else if (!this.credential.equals(other.credential))
            return false;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.credential == null) ? 0 : this.credential.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSourceCredentials (");

        sb.append(userId);
        sb.append(", ").append(credential);
        sb.append(", ").append(sourceId);

        sb.append(")");
        return sb.toString();
    }
}
