/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDomainPermissibleValue implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer valueDomainScopedIdentifierId;
    private Integer permissibleValueScopedIdentifierId;

    public ValueDomainPermissibleValue() {}

    public ValueDomainPermissibleValue(ValueDomainPermissibleValue value) {
        this.valueDomainScopedIdentifierId = value.valueDomainScopedIdentifierId;
        this.permissibleValueScopedIdentifierId = value.permissibleValueScopedIdentifierId;
    }

    public ValueDomainPermissibleValue(
        Integer valueDomainScopedIdentifierId,
        Integer permissibleValueScopedIdentifierId
    ) {
        this.valueDomainScopedIdentifierId = valueDomainScopedIdentifierId;
        this.permissibleValueScopedIdentifierId = permissibleValueScopedIdentifierId;
    }

    /**
     * Getter for
     * <code>public.value_domain_permissible_value.value_domain_scoped_identifier_id</code>.
     */
    public Integer getValueDomainScopedIdentifierId() {
        return this.valueDomainScopedIdentifierId;
    }

    /**
     * Setter for
     * <code>public.value_domain_permissible_value.value_domain_scoped_identifier_id</code>.
     */
    public void setValueDomainScopedIdentifierId(Integer valueDomainScopedIdentifierId) {
        this.valueDomainScopedIdentifierId = valueDomainScopedIdentifierId;
    }

    /**
     * Getter for
     * <code>public.value_domain_permissible_value.permissible_value_scoped_identifier_id</code>.
     */
    public Integer getPermissibleValueScopedIdentifierId() {
        return this.permissibleValueScopedIdentifierId;
    }

    /**
     * Setter for
     * <code>public.value_domain_permissible_value.permissible_value_scoped_identifier_id</code>.
     */
    public void setPermissibleValueScopedIdentifierId(Integer permissibleValueScopedIdentifierId) {
        this.permissibleValueScopedIdentifierId = permissibleValueScopedIdentifierId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ValueDomainPermissibleValue (");

        sb.append(valueDomainScopedIdentifierId);
        sb.append(", ").append(permissibleValueScopedIdentifierId);

        sb.append(")");
        return sb.toString();
    }
}
