/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables;


import de.dataelementhub.dal.jooq.Indexes;
import de.dataelementhub.dal.jooq.Keys;
import de.dataelementhub.dal.jooq.Public;
import de.dataelementhub.dal.jooq.tables.records.ScopedIdentifierHierarchyRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopedIdentifierHierarchy extends TableImpl<ScopedIdentifierHierarchyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.scoped_identifier_hierarchy</code>
     */
    public static final ScopedIdentifierHierarchy SCOPED_IDENTIFIER_HIERARCHY = new ScopedIdentifierHierarchy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScopedIdentifierHierarchyRecord> getRecordType() {
        return ScopedIdentifierHierarchyRecord.class;
    }

    /**
     * The column <code>public.scoped_identifier_hierarchy.super_id</code>.
     */
    public final TableField<ScopedIdentifierHierarchyRecord, Integer> SUPER_ID = createField(DSL.name("super_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.scoped_identifier_hierarchy.sub_id</code>.
     */
    public final TableField<ScopedIdentifierHierarchyRecord, Integer> SUB_ID = createField(DSL.name("sub_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.scoped_identifier_hierarchy.order</code>.
     */
    public final TableField<ScopedIdentifierHierarchyRecord, Integer> ORDER = createField(DSL.name("order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("1", SQLDataType.INTEGER)), this, "");

    private ScopedIdentifierHierarchy(Name alias, Table<ScopedIdentifierHierarchyRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScopedIdentifierHierarchy(Name alias, Table<ScopedIdentifierHierarchyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.scoped_identifier_hierarchy</code> table
     * reference
     */
    public ScopedIdentifierHierarchy(String alias) {
        this(DSL.name(alias), SCOPED_IDENTIFIER_HIERARCHY);
    }

    /**
     * Create an aliased <code>public.scoped_identifier_hierarchy</code> table
     * reference
     */
    public ScopedIdentifierHierarchy(Name alias) {
        this(alias, SCOPED_IDENTIFIER_HIERARCHY);
    }

    /**
     * Create a <code>public.scoped_identifier_hierarchy</code> table reference
     */
    public ScopedIdentifierHierarchy() {
        this(DSL.name("scoped_identifier_hierarchy"), null);
    }

    public <O extends Record> ScopedIdentifierHierarchy(Table<O> child, ForeignKey<O, ScopedIdentifierHierarchyRecord> key) {
        super(child, key, SCOPED_IDENTIFIER_HIERARCHY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SCOPED_IDENTIFIER_HIERARCHY_SUB_ID_IDX, Indexes.SCOPED_IDENTIFIER_HIERARCHY_SUPER_ID_IDX);
    }

    @Override
    public UniqueKey<ScopedIdentifierHierarchyRecord> getPrimaryKey() {
        return Keys.SCOPED_IDENTIFIER_HIERARCHY_PKEY;
    }

    @Override
    public List<ForeignKey<ScopedIdentifierHierarchyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SCOPED_IDENTIFIER_HIERARCHY__SCOPED_IDENTIFIER_HIERARCHY_SUPER_ID_FKEY, Keys.SCOPED_IDENTIFIER_HIERARCHY__SCOPED_IDENTIFIER_HIERARCHY_SUB_ID_FKEY);
    }

    private transient ScopedIdentifier _scopedIdentifierHierarchySuperIdFkey;
    private transient ScopedIdentifier _scopedIdentifierHierarchySubIdFkey;

    /**
     * Get the implicit join path to the <code>public.scoped_identifier</code>
     * table, via the <code>scoped_identifier_hierarchy_super_id_fkey</code>
     * key.
     */
    public ScopedIdentifier scopedIdentifierHierarchySuperIdFkey() {
        if (_scopedIdentifierHierarchySuperIdFkey == null)
            _scopedIdentifierHierarchySuperIdFkey = new ScopedIdentifier(this, Keys.SCOPED_IDENTIFIER_HIERARCHY__SCOPED_IDENTIFIER_HIERARCHY_SUPER_ID_FKEY);

        return _scopedIdentifierHierarchySuperIdFkey;
    }

    /**
     * Get the implicit join path to the <code>public.scoped_identifier</code>
     * table, via the <code>scoped_identifier_hierarchy_sub_id_fkey</code> key.
     */
    public ScopedIdentifier scopedIdentifierHierarchySubIdFkey() {
        if (_scopedIdentifierHierarchySubIdFkey == null)
            _scopedIdentifierHierarchySubIdFkey = new ScopedIdentifier(this, Keys.SCOPED_IDENTIFIER_HIERARCHY__SCOPED_IDENTIFIER_HIERARCHY_SUB_ID_FKEY);

        return _scopedIdentifierHierarchySubIdFkey;
    }

    @Override
    public ScopedIdentifierHierarchy as(String alias) {
        return new ScopedIdentifierHierarchy(DSL.name(alias), this);
    }

    @Override
    public ScopedIdentifierHierarchy as(Name alias) {
        return new ScopedIdentifierHierarchy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScopedIdentifierHierarchy rename(String name) {
        return new ScopedIdentifierHierarchy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScopedIdentifierHierarchy rename(Name name) {
        return new ScopedIdentifierHierarchy(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
