/*
 * This file is generated by jOOQ.
 */
package de.dataelementhub.dal.jooq.tables;


import de.dataelementhub.dal.jooq.Keys;
import de.dataelementhub.dal.jooq.Public;
import de.dataelementhub.dal.jooq.enums.ElementType;
import de.dataelementhub.dal.jooq.tables.records.StagingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staging extends TableImpl<StagingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.staging</code>
     */
    public static final Staging STAGING = new Staging();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StagingRecord> getRecordType() {
        return StagingRecord.class;
    }

    /**
     * The column <code>public.staging.id</code>.
     */
    public final TableField<StagingRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.staging.data</code>.
     */
    public final TableField<StagingRecord, String> DATA = createField(DSL.name("data"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.staging.element_type</code>.
     */
    public final TableField<StagingRecord, ElementType> ELEMENT_TYPE = createField(DSL.name("element_type"), SQLDataType.VARCHAR.asEnumDataType(de.dataelementhub.dal.jooq.enums.ElementType.class), this, "");

    /**
     * The column <code>public.staging.designation</code>.
     */
    public final TableField<StagingRecord, String> DESIGNATION = createField(DSL.name("designation"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.staging.import_id</code>.
     */
    public final TableField<StagingRecord, Integer> IMPORT_ID = createField(DSL.name("import_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.staging.scoped_identifier_id</code>.
     */
    public final TableField<StagingRecord, Integer> SCOPED_IDENTIFIER_ID = createField(DSL.name("scoped_identifier_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.staging.converted_at</code>.
     */
    public final TableField<StagingRecord, LocalDateTime> CONVERTED_AT = createField(DSL.name("converted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.staging.converted_by</code>.
     */
    public final TableField<StagingRecord, Integer> CONVERTED_BY = createField(DSL.name("converted_by"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.staging.staged_element_id</code>.
     */
    public final TableField<StagingRecord, String> STAGED_ELEMENT_ID = createField(DSL.name("staged_element_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.staging.members</code>.
     */
    public final TableField<StagingRecord, String> MEMBERS = createField(DSL.name("members"), SQLDataType.CLOB, this, "");

    private Staging(Name alias, Table<StagingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Staging(Name alias, Table<StagingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.staging</code> table reference
     */
    public Staging(String alias) {
        this(DSL.name(alias), STAGING);
    }

    /**
     * Create an aliased <code>public.staging</code> table reference
     */
    public Staging(Name alias) {
        this(alias, STAGING);
    }

    /**
     * Create a <code>public.staging</code> table reference
     */
    public Staging() {
        this(DSL.name("staging"), null);
    }

    public <O extends Record> Staging(Table<O> child, ForeignKey<O, StagingRecord> key) {
        super(child, key, STAGING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StagingRecord, Integer> getIdentity() {
        return (Identity<StagingRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<StagingRecord> getPrimaryKey() {
        return Keys.STAGING_PKEY;
    }

    @Override
    public List<ForeignKey<StagingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STAGING__STAGING_IMPORT_FKEY, Keys.STAGING__STAGING_SCOPED_IDENTIFIER_ID_FKEY, Keys.STAGING__STAGING_CONVERTED_BY_FKEY);
    }

    private transient Import _import_;
    private transient ScopedIdentifier _scopedIdentifier;
    private transient DehubUser _dehubUser;

    /**
     * Get the implicit join path to the <code>public.import</code> table.
     */
    public Import import_() {
        if (_import_ == null)
            _import_ = new Import(this, Keys.STAGING__STAGING_IMPORT_FKEY);

        return _import_;
    }

    /**
     * Get the implicit join path to the <code>public.scoped_identifier</code>
     * table.
     */
    public ScopedIdentifier scopedIdentifier() {
        if (_scopedIdentifier == null)
            _scopedIdentifier = new ScopedIdentifier(this, Keys.STAGING__STAGING_SCOPED_IDENTIFIER_ID_FKEY);

        return _scopedIdentifier;
    }

    /**
     * Get the implicit join path to the <code>public.dehub_user</code> table.
     */
    public DehubUser dehubUser() {
        if (_dehubUser == null)
            _dehubUser = new DehubUser(this, Keys.STAGING__STAGING_CONVERTED_BY_FKEY);

        return _dehubUser;
    }

    @Override
    public Staging as(String alias) {
        return new Staging(DSL.name(alias), this);
    }

    @Override
    public Staging as(Name alias) {
        return new Staging(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Staging rename(String name) {
        return new Staging(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Staging rename(Name name) {
        return new Staging(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, ElementType, String, Integer, Integer, LocalDateTime, Integer, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
